//
// Created by payloads on 11/22/17.
//
#ifndef UNTITLED2_ERROR_H
#define UNTITLED2_ERROR_H
typedef enum {
    CONFIG_CANT_READ,
    MYSQL_CANT_CONNECT,
    MYSQL_SQL_ERROR,
    OPTION_LOST,
    CONFIG_MYSQL_HOST_LOST,
    CONFIG_MYSQL_USER_LOST,
    CONFIG_MYSQL_PASS_LOST,
    CONFIG_MYSQL_TABLE_LOST,
    CONFIG_MYSQL_DATABSE_LOST,
    MYSQL_TABLE_NOT_CREATED,
    NOT_GIVE_DOMAIN,
    NOT_GIVE_DOMAIN_DICT,
    CANT_READ_DICT,
    UNKNOWN_ERROR
}SomeError;
#endif //UNTITLED2_ERROR_H
